class Files_Translator:
    """Class Files_Translator
    
    Parameters:

    """

    @staticmethod
    def dump2xyz(filename, final_filename = None, atoms_codes=None):
        mol = 0
        mol_coords = []
        nf = []

        if final_filename == None:
                final_filename = ".".join(filename.split(".")[:-1]) + ".xyz"
    
        with open(filename, "r", encoding="utf-8") as start_file:
            sf = start_file.readlines()
            atoms_num = int(sf[sf.index("ITEM: NUMBER OF ATOMS\n")+1])

            if atoms_codes == None:
                for line in sf:
                    if line == "ITEM: ATOMS id type x y z\n":
                        mol = 1
                        
                    elif line == "ITEM: TIMESTEP\n":
                        mol = 0
                        nf.append(str(atoms_num)+"\n")
                        nf.append("Generated by NCIL_program_package\n")
                        sorted_mol_coords = sorted(mol_coords, key=lambda x: int(x[0]))
                        mol_coords = [str(line[1]).rjust(4) + str(round(float(line[2]), 5)).rjust(16) + str(round(float(line[3]), 5)).rjust(16) + str(round(float(line[4]), 5)).rjust(16) + "\n" for line in sorted_mol_coords]
                        for atom_coords in mol_coords:
                            nf.append(atom_coords)

                        mol_coords = []
                        
                    elif mol == 1:
                        line_split = line.split()
                        mol_coords.append(line_split)
                        
                    elif mol == 0:
                        continue

            else:
                for line in sf:
                    if line == "ITEM: ATOMS id type x y z\n":
                        mol = 1
                    
                    elif line == "ITEM: TIMESTEP\n":
                        mol = 0
                        nf.append(str(atoms_num)+"\n")
                        nf.append("Generated by NCIL_program_package\n")
                        sorted_mol_coords = sorted(mol_coords, key=lambda x: int(x[0]))
                        mol_coords = [str(atoms_codes[line[1]]).rjust(4) + str(line[2]).rjust(16) + str(line[3]).rjust(16) + str(line[4]).rjust(16) + "\n" for line in sorted_mol_coords]
                        nf.extend(mol_coords)
                        mol_coords = []
                    
                    elif mol == 1:
                        line_split = line.split()
                        mol_coords.append(line_split)
                    
                    elif mol == 0:
                        continue
            
        with open(final_filename, "w", encoding="utf-8") as new_file:
            new_file.writelines(nf[2::])